# New Zealand
# North Island New Zealand:
print("                -                                  0 = Wellington")
print("                \ \                                1 = Paraparaumu")
print("                /    \                             2 = Palmerston North")
print("                 \    \                            3 = Hastings / Napier")
print("                  \    \                               (twin cities)")
print("                   \   /                           4 = Wairoa")
print("                    `  \                           5 = Gisborne")
print("                     D E                           6 = Te Karaka")
print("                     |   \                         7 = Whakatane")
print("                     |     \  ||                   8 = Murupara")
print("                     |      | ||                   9 = Rotorua")
print("                     |  C B     \                  A = Tokoroa")
print("                    /             \                B = Morrinsville")
print("                    |               \    ---\      C = Hamilton")
print("                   /       A     9  7 -/     |     D = Auckland")
print("                  -               8     6   /      E = Devonport")
print("                /                         /")
print("            /                           5|")
print("           |                             |    ")
print("            \ -                     4/ - -    ")
print("                \                 |           ")
print("                  \                \          ")
print("                   \              3/          ")
print("                    |  2        /             ")
print("                   /          /               ")
print("                  /        /                  ")
print("                  |      /                    ")
print("                  |1   /                      ")
print("                   \\0 /")